// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Organization.proto

#ifndef PROTOBUF_Organization_2eproto__INCLUDED
#define PROTOBUF_Organization_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Address.pb.h"
// @@protoc_insertion_point(includes)

namespace Diadoc {
namespace Api {
namespace Proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Organization_2eproto();
void protobuf_AssignDesc_Organization_2eproto();
void protobuf_ShutdownFile_Organization_2eproto();

class OrganizationList;
class Organization;
class Department;
class Box;

// ===================================================================

class OrganizationList : public ::google::protobuf::Message {
 public:
  OrganizationList();
  virtual ~OrganizationList();

  OrganizationList(const OrganizationList& from);

  inline OrganizationList& operator=(const OrganizationList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrganizationList& default_instance();

  void Swap(OrganizationList* other);

  // implements Message ----------------------------------------------

  OrganizationList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrganizationList& from);
  void MergeFrom(const OrganizationList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Diadoc.Api.Proto.Organization Organizations = 1;
  inline int organizations_size() const;
  inline void clear_organizations();
  static const int kOrganizationsFieldNumber = 1;
  inline const ::Diadoc::Api::Proto::Organization& organizations(int index) const;
  inline ::Diadoc::Api::Proto::Organization* mutable_organizations(int index);
  inline ::Diadoc::Api::Proto::Organization* add_organizations();
  inline const ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Organization >&
      organizations() const;
  inline ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Organization >*
      mutable_organizations();

  // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.OrganizationList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Organization > organizations_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Organization_2eproto();
  friend void protobuf_AssignDesc_Organization_2eproto();
  friend void protobuf_ShutdownFile_Organization_2eproto();

  void InitAsDefaultInstance();
  static OrganizationList* default_instance_;
};
// -------------------------------------------------------------------

class Organization : public ::google::protobuf::Message {
 public:
  Organization();
  virtual ~Organization();

  Organization(const Organization& from);

  inline Organization& operator=(const Organization& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Organization& default_instance();

  void Swap(Organization* other);

  // implements Message ----------------------------------------------

  Organization* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Organization& from);
  void MergeFrom(const Organization& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string OrgId = 1;
  inline bool has_orgid() const;
  inline void clear_orgid();
  static const int kOrgIdFieldNumber = 1;
  inline const ::std::string& orgid() const;
  inline void set_orgid(const ::std::string& value);
  inline void set_orgid(const char* value);
  inline void set_orgid(const char* value, size_t size);
  inline ::std::string* mutable_orgid();
  inline ::std::string* release_orgid();
  inline void set_allocated_orgid(::std::string* orgid);

  // required string Inn = 2;
  inline bool has_inn() const;
  inline void clear_inn();
  static const int kInnFieldNumber = 2;
  inline const ::std::string& inn() const;
  inline void set_inn(const ::std::string& value);
  inline void set_inn(const char* value);
  inline void set_inn(const char* value, size_t size);
  inline ::std::string* mutable_inn();
  inline ::std::string* release_inn();
  inline void set_allocated_inn(::std::string* inn);

  // optional string Kpp = 3;
  inline bool has_kpp() const;
  inline void clear_kpp();
  static const int kKppFieldNumber = 3;
  inline const ::std::string& kpp() const;
  inline void set_kpp(const ::std::string& value);
  inline void set_kpp(const char* value);
  inline void set_kpp(const char* value, size_t size);
  inline ::std::string* mutable_kpp();
  inline ::std::string* release_kpp();
  inline void set_allocated_kpp(::std::string* kpp);

  // required string FullName = 4;
  inline bool has_fullname() const;
  inline void clear_fullname();
  static const int kFullNameFieldNumber = 4;
  inline const ::std::string& fullname() const;
  inline void set_fullname(const ::std::string& value);
  inline void set_fullname(const char* value);
  inline void set_fullname(const char* value, size_t size);
  inline ::std::string* mutable_fullname();
  inline ::std::string* release_fullname();
  inline void set_allocated_fullname(::std::string* fullname);

  // optional string ShortName = 5;
  inline bool has_shortname() const;
  inline void clear_shortname();
  static const int kShortNameFieldNumber = 5;
  inline const ::std::string& shortname() const;
  inline void set_shortname(const ::std::string& value);
  inline void set_shortname(const char* value);
  inline void set_shortname(const char* value, size_t size);
  inline ::std::string* mutable_shortname();
  inline ::std::string* release_shortname();
  inline void set_allocated_shortname(::std::string* shortname);

  // repeated .Diadoc.Api.Proto.Box Boxes = 7;
  inline int boxes_size() const;
  inline void clear_boxes();
  static const int kBoxesFieldNumber = 7;
  inline const ::Diadoc::Api::Proto::Box& boxes(int index) const;
  inline ::Diadoc::Api::Proto::Box* mutable_boxes(int index);
  inline ::Diadoc::Api::Proto::Box* add_boxes();
  inline const ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Box >&
      boxes() const;
  inline ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Box >*
      mutable_boxes();

  // optional string Ogrn = 8;
  inline bool has_ogrn() const;
  inline void clear_ogrn();
  static const int kOgrnFieldNumber = 8;
  inline const ::std::string& ogrn() const;
  inline void set_ogrn(const ::std::string& value);
  inline void set_ogrn(const char* value);
  inline void set_ogrn(const char* value, size_t size);
  inline ::std::string* mutable_ogrn();
  inline ::std::string* release_ogrn();
  inline void set_allocated_ogrn(::std::string* ogrn);

  // optional string FnsParticipantId = 9;
  inline bool has_fnsparticipantid() const;
  inline void clear_fnsparticipantid();
  static const int kFnsParticipantIdFieldNumber = 9;
  inline const ::std::string& fnsparticipantid() const;
  inline void set_fnsparticipantid(const ::std::string& value);
  inline void set_fnsparticipantid(const char* value);
  inline void set_fnsparticipantid(const char* value, size_t size);
  inline ::std::string* mutable_fnsparticipantid();
  inline ::std::string* release_fnsparticipantid();
  inline void set_allocated_fnsparticipantid(::std::string* fnsparticipantid);

  // optional .Diadoc.Api.Proto.Address Address = 10;
  inline bool has_address() const;
  inline void clear_address();
  static const int kAddressFieldNumber = 10;
  inline const ::Diadoc::Api::Proto::Address& address() const;
  inline ::Diadoc::Api::Proto::Address* mutable_address();
  inline ::Diadoc::Api::Proto::Address* release_address();
  inline void set_allocated_address(::Diadoc::Api::Proto::Address* address);

  // optional string FnsRegistrationDate = 11;
  inline bool has_fnsregistrationdate() const;
  inline void clear_fnsregistrationdate();
  static const int kFnsRegistrationDateFieldNumber = 11;
  inline const ::std::string& fnsregistrationdate() const;
  inline void set_fnsregistrationdate(const ::std::string& value);
  inline void set_fnsregistrationdate(const char* value);
  inline void set_fnsregistrationdate(const char* value, size_t size);
  inline ::std::string* mutable_fnsregistrationdate();
  inline ::std::string* release_fnsregistrationdate();
  inline void set_allocated_fnsregistrationdate(::std::string* fnsregistrationdate);

  // repeated .Diadoc.Api.Proto.Department Departments = 12;
  inline int departments_size() const;
  inline void clear_departments();
  static const int kDepartmentsFieldNumber = 12;
  inline const ::Diadoc::Api::Proto::Department& departments(int index) const;
  inline ::Diadoc::Api::Proto::Department* mutable_departments(int index);
  inline ::Diadoc::Api::Proto::Department* add_departments();
  inline const ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Department >&
      departments() const;
  inline ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Department >*
      mutable_departments();

  // optional string IfnsCode = 13;
  inline bool has_ifnscode() const;
  inline void clear_ifnscode();
  static const int kIfnsCodeFieldNumber = 13;
  inline const ::std::string& ifnscode() const;
  inline void set_ifnscode(const ::std::string& value);
  inline void set_ifnscode(const char* value);
  inline void set_ifnscode(const char* value, size_t size);
  inline ::std::string* mutable_ifnscode();
  inline ::std::string* release_ifnscode();
  inline void set_allocated_ifnscode(::std::string* ifnscode);

  // optional bool IsPilot = 14;
  inline bool has_ispilot() const;
  inline void clear_ispilot();
  static const int kIsPilotFieldNumber = 14;
  inline bool ispilot() const;
  inline void set_ispilot(bool value);

  // optional bool IsActive = 15;
  inline bool has_isactive() const;
  inline void clear_isactive();
  static const int kIsActiveFieldNumber = 15;
  inline bool isactive() const;
  inline void set_isactive(bool value);

  // optional bool IsTest = 16;
  inline bool has_istest() const;
  inline void clear_istest();
  static const int kIsTestFieldNumber = 16;
  inline bool istest() const;
  inline void set_istest(bool value);

  // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.Organization)
 private:
  inline void set_has_orgid();
  inline void clear_has_orgid();
  inline void set_has_inn();
  inline void clear_has_inn();
  inline void set_has_kpp();
  inline void clear_has_kpp();
  inline void set_has_fullname();
  inline void clear_has_fullname();
  inline void set_has_shortname();
  inline void clear_has_shortname();
  inline void set_has_ogrn();
  inline void clear_has_ogrn();
  inline void set_has_fnsparticipantid();
  inline void clear_has_fnsparticipantid();
  inline void set_has_address();
  inline void clear_has_address();
  inline void set_has_fnsregistrationdate();
  inline void clear_has_fnsregistrationdate();
  inline void set_has_ifnscode();
  inline void clear_has_ifnscode();
  inline void set_has_ispilot();
  inline void clear_has_ispilot();
  inline void set_has_isactive();
  inline void clear_has_isactive();
  inline void set_has_istest();
  inline void clear_has_istest();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* orgid_;
  ::std::string* inn_;
  ::std::string* kpp_;
  ::std::string* fullname_;
  ::std::string* shortname_;
  ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Box > boxes_;
  ::std::string* ogrn_;
  ::std::string* fnsparticipantid_;
  ::Diadoc::Api::Proto::Address* address_;
  ::std::string* fnsregistrationdate_;
  ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Department > departments_;
  ::std::string* ifnscode_;
  bool ispilot_;
  bool isactive_;
  bool istest_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(15 + 31) / 32];

  friend void  protobuf_AddDesc_Organization_2eproto();
  friend void protobuf_AssignDesc_Organization_2eproto();
  friend void protobuf_ShutdownFile_Organization_2eproto();

  void InitAsDefaultInstance();
  static Organization* default_instance_;
};
// -------------------------------------------------------------------

class Department : public ::google::protobuf::Message {
 public:
  Department();
  virtual ~Department();

  Department(const Department& from);

  inline Department& operator=(const Department& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Department& default_instance();

  void Swap(Department* other);

  // implements Message ----------------------------------------------

  Department* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Department& from);
  void MergeFrom(const Department& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string DepartmentId = 1;
  inline bool has_departmentid() const;
  inline void clear_departmentid();
  static const int kDepartmentIdFieldNumber = 1;
  inline const ::std::string& departmentid() const;
  inline void set_departmentid(const ::std::string& value);
  inline void set_departmentid(const char* value);
  inline void set_departmentid(const char* value, size_t size);
  inline ::std::string* mutable_departmentid();
  inline ::std::string* release_departmentid();
  inline void set_allocated_departmentid(::std::string* departmentid);

  // required string ParentDepartmentId = 2;
  inline bool has_parentdepartmentid() const;
  inline void clear_parentdepartmentid();
  static const int kParentDepartmentIdFieldNumber = 2;
  inline const ::std::string& parentdepartmentid() const;
  inline void set_parentdepartmentid(const ::std::string& value);
  inline void set_parentdepartmentid(const char* value);
  inline void set_parentdepartmentid(const char* value, size_t size);
  inline ::std::string* mutable_parentdepartmentid();
  inline ::std::string* release_parentdepartmentid();
  inline void set_allocated_parentdepartmentid(::std::string* parentdepartmentid);

  // required string Name = 3;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 3;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string Abbreviation = 4;
  inline bool has_abbreviation() const;
  inline void clear_abbreviation();
  static const int kAbbreviationFieldNumber = 4;
  inline const ::std::string& abbreviation() const;
  inline void set_abbreviation(const ::std::string& value);
  inline void set_abbreviation(const char* value);
  inline void set_abbreviation(const char* value, size_t size);
  inline ::std::string* mutable_abbreviation();
  inline ::std::string* release_abbreviation();
  inline void set_allocated_abbreviation(::std::string* abbreviation);

  // optional string Kpp = 5;
  inline bool has_kpp() const;
  inline void clear_kpp();
  static const int kKppFieldNumber = 5;
  inline const ::std::string& kpp() const;
  inline void set_kpp(const ::std::string& value);
  inline void set_kpp(const char* value);
  inline void set_kpp(const char* value, size_t size);
  inline ::std::string* mutable_kpp();
  inline ::std::string* release_kpp();
  inline void set_allocated_kpp(::std::string* kpp);

  // optional .Diadoc.Api.Proto.Address Address = 6;
  inline bool has_address() const;
  inline void clear_address();
  static const int kAddressFieldNumber = 6;
  inline const ::Diadoc::Api::Proto::Address& address() const;
  inline ::Diadoc::Api::Proto::Address* mutable_address();
  inline ::Diadoc::Api::Proto::Address* release_address();
  inline void set_allocated_address(::Diadoc::Api::Proto::Address* address);

  // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.Department)
 private:
  inline void set_has_departmentid();
  inline void clear_has_departmentid();
  inline void set_has_parentdepartmentid();
  inline void clear_has_parentdepartmentid();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_abbreviation();
  inline void clear_has_abbreviation();
  inline void set_has_kpp();
  inline void clear_has_kpp();
  inline void set_has_address();
  inline void clear_has_address();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* departmentid_;
  ::std::string* parentdepartmentid_;
  ::std::string* name_;
  ::std::string* abbreviation_;
  ::std::string* kpp_;
  ::Diadoc::Api::Proto::Address* address_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_Organization_2eproto();
  friend void protobuf_AssignDesc_Organization_2eproto();
  friend void protobuf_ShutdownFile_Organization_2eproto();

  void InitAsDefaultInstance();
  static Department* default_instance_;
};
// -------------------------------------------------------------------

class Box : public ::google::protobuf::Message {
 public:
  Box();
  virtual ~Box();

  Box(const Box& from);

  inline Box& operator=(const Box& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Box& default_instance();

  void Swap(Box* other);

  // implements Message ----------------------------------------------

  Box* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Box& from);
  void MergeFrom(const Box& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string BoxId = 1;
  inline bool has_boxid() const;
  inline void clear_boxid();
  static const int kBoxIdFieldNumber = 1;
  inline const ::std::string& boxid() const;
  inline void set_boxid(const ::std::string& value);
  inline void set_boxid(const char* value);
  inline void set_boxid(const char* value, size_t size);
  inline ::std::string* mutable_boxid();
  inline ::std::string* release_boxid();
  inline void set_allocated_boxid(::std::string* boxid);

  // required string Title = 2;
  inline bool has_title() const;
  inline void clear_title();
  static const int kTitleFieldNumber = 2;
  inline const ::std::string& title() const;
  inline void set_title(const ::std::string& value);
  inline void set_title(const char* value);
  inline void set_title(const char* value, size_t size);
  inline ::std::string* mutable_title();
  inline ::std::string* release_title();
  inline void set_allocated_title(::std::string* title);

  // optional .Diadoc.Api.Proto.Organization Organization = 3;
  inline bool has_organization() const;
  inline void clear_organization();
  static const int kOrganizationFieldNumber = 3;
  inline const ::Diadoc::Api::Proto::Organization& organization() const;
  inline ::Diadoc::Api::Proto::Organization* mutable_organization();
  inline ::Diadoc::Api::Proto::Organization* release_organization();
  inline void set_allocated_organization(::Diadoc::Api::Proto::Organization* organization);

  // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.Box)
 private:
  inline void set_has_boxid();
  inline void clear_has_boxid();
  inline void set_has_title();
  inline void clear_has_title();
  inline void set_has_organization();
  inline void clear_has_organization();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* boxid_;
  ::std::string* title_;
  ::Diadoc::Api::Proto::Organization* organization_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Organization_2eproto();
  friend void protobuf_AssignDesc_Organization_2eproto();
  friend void protobuf_ShutdownFile_Organization_2eproto();

  void InitAsDefaultInstance();
  static Box* default_instance_;
};
// ===================================================================


// ===================================================================

// OrganizationList

// repeated .Diadoc.Api.Proto.Organization Organizations = 1;
inline int OrganizationList::organizations_size() const {
  return organizations_.size();
}
inline void OrganizationList::clear_organizations() {
  organizations_.Clear();
}
inline const ::Diadoc::Api::Proto::Organization& OrganizationList::organizations(int index) const {
  return organizations_.Get(index);
}
inline ::Diadoc::Api::Proto::Organization* OrganizationList::mutable_organizations(int index) {
  return organizations_.Mutable(index);
}
inline ::Diadoc::Api::Proto::Organization* OrganizationList::add_organizations() {
  return organizations_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Organization >&
OrganizationList::organizations() const {
  return organizations_;
}
inline ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Organization >*
OrganizationList::mutable_organizations() {
  return &organizations_;
}

// -------------------------------------------------------------------

// Organization

// required string OrgId = 1;
inline bool Organization::has_orgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Organization::set_has_orgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Organization::clear_has_orgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Organization::clear_orgid() {
  if (orgid_ != &::google::protobuf::internal::kEmptyString) {
    orgid_->clear();
  }
  clear_has_orgid();
}
inline const ::std::string& Organization::orgid() const {
  return *orgid_;
}
inline void Organization::set_orgid(const ::std::string& value) {
  set_has_orgid();
  if (orgid_ == &::google::protobuf::internal::kEmptyString) {
    orgid_ = new ::std::string;
  }
  orgid_->assign(value);
}
inline void Organization::set_orgid(const char* value) {
  set_has_orgid();
  if (orgid_ == &::google::protobuf::internal::kEmptyString) {
    orgid_ = new ::std::string;
  }
  orgid_->assign(value);
}
inline void Organization::set_orgid(const char* value, size_t size) {
  set_has_orgid();
  if (orgid_ == &::google::protobuf::internal::kEmptyString) {
    orgid_ = new ::std::string;
  }
  orgid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Organization::mutable_orgid() {
  set_has_orgid();
  if (orgid_ == &::google::protobuf::internal::kEmptyString) {
    orgid_ = new ::std::string;
  }
  return orgid_;
}
inline ::std::string* Organization::release_orgid() {
  clear_has_orgid();
  if (orgid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = orgid_;
    orgid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Organization::set_allocated_orgid(::std::string* orgid) {
  if (orgid_ != &::google::protobuf::internal::kEmptyString) {
    delete orgid_;
  }
  if (orgid) {
    set_has_orgid();
    orgid_ = orgid;
  } else {
    clear_has_orgid();
    orgid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string Inn = 2;
inline bool Organization::has_inn() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Organization::set_has_inn() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Organization::clear_has_inn() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Organization::clear_inn() {
  if (inn_ != &::google::protobuf::internal::kEmptyString) {
    inn_->clear();
  }
  clear_has_inn();
}
inline const ::std::string& Organization::inn() const {
  return *inn_;
}
inline void Organization::set_inn(const ::std::string& value) {
  set_has_inn();
  if (inn_ == &::google::protobuf::internal::kEmptyString) {
    inn_ = new ::std::string;
  }
  inn_->assign(value);
}
inline void Organization::set_inn(const char* value) {
  set_has_inn();
  if (inn_ == &::google::protobuf::internal::kEmptyString) {
    inn_ = new ::std::string;
  }
  inn_->assign(value);
}
inline void Organization::set_inn(const char* value, size_t size) {
  set_has_inn();
  if (inn_ == &::google::protobuf::internal::kEmptyString) {
    inn_ = new ::std::string;
  }
  inn_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Organization::mutable_inn() {
  set_has_inn();
  if (inn_ == &::google::protobuf::internal::kEmptyString) {
    inn_ = new ::std::string;
  }
  return inn_;
}
inline ::std::string* Organization::release_inn() {
  clear_has_inn();
  if (inn_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = inn_;
    inn_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Organization::set_allocated_inn(::std::string* inn) {
  if (inn_ != &::google::protobuf::internal::kEmptyString) {
    delete inn_;
  }
  if (inn) {
    set_has_inn();
    inn_ = inn;
  } else {
    clear_has_inn();
    inn_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string Kpp = 3;
inline bool Organization::has_kpp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Organization::set_has_kpp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Organization::clear_has_kpp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Organization::clear_kpp() {
  if (kpp_ != &::google::protobuf::internal::kEmptyString) {
    kpp_->clear();
  }
  clear_has_kpp();
}
inline const ::std::string& Organization::kpp() const {
  return *kpp_;
}
inline void Organization::set_kpp(const ::std::string& value) {
  set_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    kpp_ = new ::std::string;
  }
  kpp_->assign(value);
}
inline void Organization::set_kpp(const char* value) {
  set_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    kpp_ = new ::std::string;
  }
  kpp_->assign(value);
}
inline void Organization::set_kpp(const char* value, size_t size) {
  set_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    kpp_ = new ::std::string;
  }
  kpp_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Organization::mutable_kpp() {
  set_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    kpp_ = new ::std::string;
  }
  return kpp_;
}
inline ::std::string* Organization::release_kpp() {
  clear_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = kpp_;
    kpp_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Organization::set_allocated_kpp(::std::string* kpp) {
  if (kpp_ != &::google::protobuf::internal::kEmptyString) {
    delete kpp_;
  }
  if (kpp) {
    set_has_kpp();
    kpp_ = kpp;
  } else {
    clear_has_kpp();
    kpp_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string FullName = 4;
inline bool Organization::has_fullname() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Organization::set_has_fullname() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Organization::clear_has_fullname() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Organization::clear_fullname() {
  if (fullname_ != &::google::protobuf::internal::kEmptyString) {
    fullname_->clear();
  }
  clear_has_fullname();
}
inline const ::std::string& Organization::fullname() const {
  return *fullname_;
}
inline void Organization::set_fullname(const ::std::string& value) {
  set_has_fullname();
  if (fullname_ == &::google::protobuf::internal::kEmptyString) {
    fullname_ = new ::std::string;
  }
  fullname_->assign(value);
}
inline void Organization::set_fullname(const char* value) {
  set_has_fullname();
  if (fullname_ == &::google::protobuf::internal::kEmptyString) {
    fullname_ = new ::std::string;
  }
  fullname_->assign(value);
}
inline void Organization::set_fullname(const char* value, size_t size) {
  set_has_fullname();
  if (fullname_ == &::google::protobuf::internal::kEmptyString) {
    fullname_ = new ::std::string;
  }
  fullname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Organization::mutable_fullname() {
  set_has_fullname();
  if (fullname_ == &::google::protobuf::internal::kEmptyString) {
    fullname_ = new ::std::string;
  }
  return fullname_;
}
inline ::std::string* Organization::release_fullname() {
  clear_has_fullname();
  if (fullname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = fullname_;
    fullname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Organization::set_allocated_fullname(::std::string* fullname) {
  if (fullname_ != &::google::protobuf::internal::kEmptyString) {
    delete fullname_;
  }
  if (fullname) {
    set_has_fullname();
    fullname_ = fullname;
  } else {
    clear_has_fullname();
    fullname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string ShortName = 5;
inline bool Organization::has_shortname() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Organization::set_has_shortname() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Organization::clear_has_shortname() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Organization::clear_shortname() {
  if (shortname_ != &::google::protobuf::internal::kEmptyString) {
    shortname_->clear();
  }
  clear_has_shortname();
}
inline const ::std::string& Organization::shortname() const {
  return *shortname_;
}
inline void Organization::set_shortname(const ::std::string& value) {
  set_has_shortname();
  if (shortname_ == &::google::protobuf::internal::kEmptyString) {
    shortname_ = new ::std::string;
  }
  shortname_->assign(value);
}
inline void Organization::set_shortname(const char* value) {
  set_has_shortname();
  if (shortname_ == &::google::protobuf::internal::kEmptyString) {
    shortname_ = new ::std::string;
  }
  shortname_->assign(value);
}
inline void Organization::set_shortname(const char* value, size_t size) {
  set_has_shortname();
  if (shortname_ == &::google::protobuf::internal::kEmptyString) {
    shortname_ = new ::std::string;
  }
  shortname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Organization::mutable_shortname() {
  set_has_shortname();
  if (shortname_ == &::google::protobuf::internal::kEmptyString) {
    shortname_ = new ::std::string;
  }
  return shortname_;
}
inline ::std::string* Organization::release_shortname() {
  clear_has_shortname();
  if (shortname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = shortname_;
    shortname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Organization::set_allocated_shortname(::std::string* shortname) {
  if (shortname_ != &::google::protobuf::internal::kEmptyString) {
    delete shortname_;
  }
  if (shortname) {
    set_has_shortname();
    shortname_ = shortname;
  } else {
    clear_has_shortname();
    shortname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .Diadoc.Api.Proto.Box Boxes = 7;
inline int Organization::boxes_size() const {
  return boxes_.size();
}
inline void Organization::clear_boxes() {
  boxes_.Clear();
}
inline const ::Diadoc::Api::Proto::Box& Organization::boxes(int index) const {
  return boxes_.Get(index);
}
inline ::Diadoc::Api::Proto::Box* Organization::mutable_boxes(int index) {
  return boxes_.Mutable(index);
}
inline ::Diadoc::Api::Proto::Box* Organization::add_boxes() {
  return boxes_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Box >&
Organization::boxes() const {
  return boxes_;
}
inline ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Box >*
Organization::mutable_boxes() {
  return &boxes_;
}

// optional string Ogrn = 8;
inline bool Organization::has_ogrn() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Organization::set_has_ogrn() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Organization::clear_has_ogrn() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Organization::clear_ogrn() {
  if (ogrn_ != &::google::protobuf::internal::kEmptyString) {
    ogrn_->clear();
  }
  clear_has_ogrn();
}
inline const ::std::string& Organization::ogrn() const {
  return *ogrn_;
}
inline void Organization::set_ogrn(const ::std::string& value) {
  set_has_ogrn();
  if (ogrn_ == &::google::protobuf::internal::kEmptyString) {
    ogrn_ = new ::std::string;
  }
  ogrn_->assign(value);
}
inline void Organization::set_ogrn(const char* value) {
  set_has_ogrn();
  if (ogrn_ == &::google::protobuf::internal::kEmptyString) {
    ogrn_ = new ::std::string;
  }
  ogrn_->assign(value);
}
inline void Organization::set_ogrn(const char* value, size_t size) {
  set_has_ogrn();
  if (ogrn_ == &::google::protobuf::internal::kEmptyString) {
    ogrn_ = new ::std::string;
  }
  ogrn_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Organization::mutable_ogrn() {
  set_has_ogrn();
  if (ogrn_ == &::google::protobuf::internal::kEmptyString) {
    ogrn_ = new ::std::string;
  }
  return ogrn_;
}
inline ::std::string* Organization::release_ogrn() {
  clear_has_ogrn();
  if (ogrn_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ogrn_;
    ogrn_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Organization::set_allocated_ogrn(::std::string* ogrn) {
  if (ogrn_ != &::google::protobuf::internal::kEmptyString) {
    delete ogrn_;
  }
  if (ogrn) {
    set_has_ogrn();
    ogrn_ = ogrn;
  } else {
    clear_has_ogrn();
    ogrn_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string FnsParticipantId = 9;
inline bool Organization::has_fnsparticipantid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Organization::set_has_fnsparticipantid() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Organization::clear_has_fnsparticipantid() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Organization::clear_fnsparticipantid() {
  if (fnsparticipantid_ != &::google::protobuf::internal::kEmptyString) {
    fnsparticipantid_->clear();
  }
  clear_has_fnsparticipantid();
}
inline const ::std::string& Organization::fnsparticipantid() const {
  return *fnsparticipantid_;
}
inline void Organization::set_fnsparticipantid(const ::std::string& value) {
  set_has_fnsparticipantid();
  if (fnsparticipantid_ == &::google::protobuf::internal::kEmptyString) {
    fnsparticipantid_ = new ::std::string;
  }
  fnsparticipantid_->assign(value);
}
inline void Organization::set_fnsparticipantid(const char* value) {
  set_has_fnsparticipantid();
  if (fnsparticipantid_ == &::google::protobuf::internal::kEmptyString) {
    fnsparticipantid_ = new ::std::string;
  }
  fnsparticipantid_->assign(value);
}
inline void Organization::set_fnsparticipantid(const char* value, size_t size) {
  set_has_fnsparticipantid();
  if (fnsparticipantid_ == &::google::protobuf::internal::kEmptyString) {
    fnsparticipantid_ = new ::std::string;
  }
  fnsparticipantid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Organization::mutable_fnsparticipantid() {
  set_has_fnsparticipantid();
  if (fnsparticipantid_ == &::google::protobuf::internal::kEmptyString) {
    fnsparticipantid_ = new ::std::string;
  }
  return fnsparticipantid_;
}
inline ::std::string* Organization::release_fnsparticipantid() {
  clear_has_fnsparticipantid();
  if (fnsparticipantid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = fnsparticipantid_;
    fnsparticipantid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Organization::set_allocated_fnsparticipantid(::std::string* fnsparticipantid) {
  if (fnsparticipantid_ != &::google::protobuf::internal::kEmptyString) {
    delete fnsparticipantid_;
  }
  if (fnsparticipantid) {
    set_has_fnsparticipantid();
    fnsparticipantid_ = fnsparticipantid;
  } else {
    clear_has_fnsparticipantid();
    fnsparticipantid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .Diadoc.Api.Proto.Address Address = 10;
inline bool Organization::has_address() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Organization::set_has_address() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Organization::clear_has_address() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Organization::clear_address() {
  if (address_ != NULL) address_->::Diadoc::Api::Proto::Address::Clear();
  clear_has_address();
}
inline const ::Diadoc::Api::Proto::Address& Organization::address() const {
  return address_ != NULL ? *address_ : *default_instance_->address_;
}
inline ::Diadoc::Api::Proto::Address* Organization::mutable_address() {
  set_has_address();
  if (address_ == NULL) address_ = new ::Diadoc::Api::Proto::Address;
  return address_;
}
inline ::Diadoc::Api::Proto::Address* Organization::release_address() {
  clear_has_address();
  ::Diadoc::Api::Proto::Address* temp = address_;
  address_ = NULL;
  return temp;
}
inline void Organization::set_allocated_address(::Diadoc::Api::Proto::Address* address) {
  delete address_;
  address_ = address;
  if (address) {
    set_has_address();
  } else {
    clear_has_address();
  }
}

// optional string FnsRegistrationDate = 11;
inline bool Organization::has_fnsregistrationdate() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Organization::set_has_fnsregistrationdate() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Organization::clear_has_fnsregistrationdate() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Organization::clear_fnsregistrationdate() {
  if (fnsregistrationdate_ != &::google::protobuf::internal::kEmptyString) {
    fnsregistrationdate_->clear();
  }
  clear_has_fnsregistrationdate();
}
inline const ::std::string& Organization::fnsregistrationdate() const {
  return *fnsregistrationdate_;
}
inline void Organization::set_fnsregistrationdate(const ::std::string& value) {
  set_has_fnsregistrationdate();
  if (fnsregistrationdate_ == &::google::protobuf::internal::kEmptyString) {
    fnsregistrationdate_ = new ::std::string;
  }
  fnsregistrationdate_->assign(value);
}
inline void Organization::set_fnsregistrationdate(const char* value) {
  set_has_fnsregistrationdate();
  if (fnsregistrationdate_ == &::google::protobuf::internal::kEmptyString) {
    fnsregistrationdate_ = new ::std::string;
  }
  fnsregistrationdate_->assign(value);
}
inline void Organization::set_fnsregistrationdate(const char* value, size_t size) {
  set_has_fnsregistrationdate();
  if (fnsregistrationdate_ == &::google::protobuf::internal::kEmptyString) {
    fnsregistrationdate_ = new ::std::string;
  }
  fnsregistrationdate_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Organization::mutable_fnsregistrationdate() {
  set_has_fnsregistrationdate();
  if (fnsregistrationdate_ == &::google::protobuf::internal::kEmptyString) {
    fnsregistrationdate_ = new ::std::string;
  }
  return fnsregistrationdate_;
}
inline ::std::string* Organization::release_fnsregistrationdate() {
  clear_has_fnsregistrationdate();
  if (fnsregistrationdate_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = fnsregistrationdate_;
    fnsregistrationdate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Organization::set_allocated_fnsregistrationdate(::std::string* fnsregistrationdate) {
  if (fnsregistrationdate_ != &::google::protobuf::internal::kEmptyString) {
    delete fnsregistrationdate_;
  }
  if (fnsregistrationdate) {
    set_has_fnsregistrationdate();
    fnsregistrationdate_ = fnsregistrationdate;
  } else {
    clear_has_fnsregistrationdate();
    fnsregistrationdate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .Diadoc.Api.Proto.Department Departments = 12;
inline int Organization::departments_size() const {
  return departments_.size();
}
inline void Organization::clear_departments() {
  departments_.Clear();
}
inline const ::Diadoc::Api::Proto::Department& Organization::departments(int index) const {
  return departments_.Get(index);
}
inline ::Diadoc::Api::Proto::Department* Organization::mutable_departments(int index) {
  return departments_.Mutable(index);
}
inline ::Diadoc::Api::Proto::Department* Organization::add_departments() {
  return departments_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Department >&
Organization::departments() const {
  return departments_;
}
inline ::google::protobuf::RepeatedPtrField< ::Diadoc::Api::Proto::Department >*
Organization::mutable_departments() {
  return &departments_;
}

// optional string IfnsCode = 13;
inline bool Organization::has_ifnscode() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Organization::set_has_ifnscode() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Organization::clear_has_ifnscode() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Organization::clear_ifnscode() {
  if (ifnscode_ != &::google::protobuf::internal::kEmptyString) {
    ifnscode_->clear();
  }
  clear_has_ifnscode();
}
inline const ::std::string& Organization::ifnscode() const {
  return *ifnscode_;
}
inline void Organization::set_ifnscode(const ::std::string& value) {
  set_has_ifnscode();
  if (ifnscode_ == &::google::protobuf::internal::kEmptyString) {
    ifnscode_ = new ::std::string;
  }
  ifnscode_->assign(value);
}
inline void Organization::set_ifnscode(const char* value) {
  set_has_ifnscode();
  if (ifnscode_ == &::google::protobuf::internal::kEmptyString) {
    ifnscode_ = new ::std::string;
  }
  ifnscode_->assign(value);
}
inline void Organization::set_ifnscode(const char* value, size_t size) {
  set_has_ifnscode();
  if (ifnscode_ == &::google::protobuf::internal::kEmptyString) {
    ifnscode_ = new ::std::string;
  }
  ifnscode_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Organization::mutable_ifnscode() {
  set_has_ifnscode();
  if (ifnscode_ == &::google::protobuf::internal::kEmptyString) {
    ifnscode_ = new ::std::string;
  }
  return ifnscode_;
}
inline ::std::string* Organization::release_ifnscode() {
  clear_has_ifnscode();
  if (ifnscode_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ifnscode_;
    ifnscode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Organization::set_allocated_ifnscode(::std::string* ifnscode) {
  if (ifnscode_ != &::google::protobuf::internal::kEmptyString) {
    delete ifnscode_;
  }
  if (ifnscode) {
    set_has_ifnscode();
    ifnscode_ = ifnscode;
  } else {
    clear_has_ifnscode();
    ifnscode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bool IsPilot = 14;
inline bool Organization::has_ispilot() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Organization::set_has_ispilot() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Organization::clear_has_ispilot() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Organization::clear_ispilot() {
  ispilot_ = false;
  clear_has_ispilot();
}
inline bool Organization::ispilot() const {
  return ispilot_;
}
inline void Organization::set_ispilot(bool value) {
  set_has_ispilot();
  ispilot_ = value;
}

// optional bool IsActive = 15;
inline bool Organization::has_isactive() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void Organization::set_has_isactive() {
  _has_bits_[0] |= 0x00002000u;
}
inline void Organization::clear_has_isactive() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void Organization::clear_isactive() {
  isactive_ = false;
  clear_has_isactive();
}
inline bool Organization::isactive() const {
  return isactive_;
}
inline void Organization::set_isactive(bool value) {
  set_has_isactive();
  isactive_ = value;
}

// optional bool IsTest = 16;
inline bool Organization::has_istest() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void Organization::set_has_istest() {
  _has_bits_[0] |= 0x00004000u;
}
inline void Organization::clear_has_istest() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void Organization::clear_istest() {
  istest_ = false;
  clear_has_istest();
}
inline bool Organization::istest() const {
  return istest_;
}
inline void Organization::set_istest(bool value) {
  set_has_istest();
  istest_ = value;
}

// -------------------------------------------------------------------

// Department

// required string DepartmentId = 1;
inline bool Department::has_departmentid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Department::set_has_departmentid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Department::clear_has_departmentid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Department::clear_departmentid() {
  if (departmentid_ != &::google::protobuf::internal::kEmptyString) {
    departmentid_->clear();
  }
  clear_has_departmentid();
}
inline const ::std::string& Department::departmentid() const {
  return *departmentid_;
}
inline void Department::set_departmentid(const ::std::string& value) {
  set_has_departmentid();
  if (departmentid_ == &::google::protobuf::internal::kEmptyString) {
    departmentid_ = new ::std::string;
  }
  departmentid_->assign(value);
}
inline void Department::set_departmentid(const char* value) {
  set_has_departmentid();
  if (departmentid_ == &::google::protobuf::internal::kEmptyString) {
    departmentid_ = new ::std::string;
  }
  departmentid_->assign(value);
}
inline void Department::set_departmentid(const char* value, size_t size) {
  set_has_departmentid();
  if (departmentid_ == &::google::protobuf::internal::kEmptyString) {
    departmentid_ = new ::std::string;
  }
  departmentid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Department::mutable_departmentid() {
  set_has_departmentid();
  if (departmentid_ == &::google::protobuf::internal::kEmptyString) {
    departmentid_ = new ::std::string;
  }
  return departmentid_;
}
inline ::std::string* Department::release_departmentid() {
  clear_has_departmentid();
  if (departmentid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = departmentid_;
    departmentid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Department::set_allocated_departmentid(::std::string* departmentid) {
  if (departmentid_ != &::google::protobuf::internal::kEmptyString) {
    delete departmentid_;
  }
  if (departmentid) {
    set_has_departmentid();
    departmentid_ = departmentid;
  } else {
    clear_has_departmentid();
    departmentid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string ParentDepartmentId = 2;
inline bool Department::has_parentdepartmentid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Department::set_has_parentdepartmentid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Department::clear_has_parentdepartmentid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Department::clear_parentdepartmentid() {
  if (parentdepartmentid_ != &::google::protobuf::internal::kEmptyString) {
    parentdepartmentid_->clear();
  }
  clear_has_parentdepartmentid();
}
inline const ::std::string& Department::parentdepartmentid() const {
  return *parentdepartmentid_;
}
inline void Department::set_parentdepartmentid(const ::std::string& value) {
  set_has_parentdepartmentid();
  if (parentdepartmentid_ == &::google::protobuf::internal::kEmptyString) {
    parentdepartmentid_ = new ::std::string;
  }
  parentdepartmentid_->assign(value);
}
inline void Department::set_parentdepartmentid(const char* value) {
  set_has_parentdepartmentid();
  if (parentdepartmentid_ == &::google::protobuf::internal::kEmptyString) {
    parentdepartmentid_ = new ::std::string;
  }
  parentdepartmentid_->assign(value);
}
inline void Department::set_parentdepartmentid(const char* value, size_t size) {
  set_has_parentdepartmentid();
  if (parentdepartmentid_ == &::google::protobuf::internal::kEmptyString) {
    parentdepartmentid_ = new ::std::string;
  }
  parentdepartmentid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Department::mutable_parentdepartmentid() {
  set_has_parentdepartmentid();
  if (parentdepartmentid_ == &::google::protobuf::internal::kEmptyString) {
    parentdepartmentid_ = new ::std::string;
  }
  return parentdepartmentid_;
}
inline ::std::string* Department::release_parentdepartmentid() {
  clear_has_parentdepartmentid();
  if (parentdepartmentid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = parentdepartmentid_;
    parentdepartmentid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Department::set_allocated_parentdepartmentid(::std::string* parentdepartmentid) {
  if (parentdepartmentid_ != &::google::protobuf::internal::kEmptyString) {
    delete parentdepartmentid_;
  }
  if (parentdepartmentid) {
    set_has_parentdepartmentid();
    parentdepartmentid_ = parentdepartmentid;
  } else {
    clear_has_parentdepartmentid();
    parentdepartmentid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string Name = 3;
inline bool Department::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Department::set_has_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Department::clear_has_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Department::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Department::name() const {
  return *name_;
}
inline void Department::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Department::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Department::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Department::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Department::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Department::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string Abbreviation = 4;
inline bool Department::has_abbreviation() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Department::set_has_abbreviation() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Department::clear_has_abbreviation() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Department::clear_abbreviation() {
  if (abbreviation_ != &::google::protobuf::internal::kEmptyString) {
    abbreviation_->clear();
  }
  clear_has_abbreviation();
}
inline const ::std::string& Department::abbreviation() const {
  return *abbreviation_;
}
inline void Department::set_abbreviation(const ::std::string& value) {
  set_has_abbreviation();
  if (abbreviation_ == &::google::protobuf::internal::kEmptyString) {
    abbreviation_ = new ::std::string;
  }
  abbreviation_->assign(value);
}
inline void Department::set_abbreviation(const char* value) {
  set_has_abbreviation();
  if (abbreviation_ == &::google::protobuf::internal::kEmptyString) {
    abbreviation_ = new ::std::string;
  }
  abbreviation_->assign(value);
}
inline void Department::set_abbreviation(const char* value, size_t size) {
  set_has_abbreviation();
  if (abbreviation_ == &::google::protobuf::internal::kEmptyString) {
    abbreviation_ = new ::std::string;
  }
  abbreviation_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Department::mutable_abbreviation() {
  set_has_abbreviation();
  if (abbreviation_ == &::google::protobuf::internal::kEmptyString) {
    abbreviation_ = new ::std::string;
  }
  return abbreviation_;
}
inline ::std::string* Department::release_abbreviation() {
  clear_has_abbreviation();
  if (abbreviation_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = abbreviation_;
    abbreviation_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Department::set_allocated_abbreviation(::std::string* abbreviation) {
  if (abbreviation_ != &::google::protobuf::internal::kEmptyString) {
    delete abbreviation_;
  }
  if (abbreviation) {
    set_has_abbreviation();
    abbreviation_ = abbreviation;
  } else {
    clear_has_abbreviation();
    abbreviation_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string Kpp = 5;
inline bool Department::has_kpp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Department::set_has_kpp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Department::clear_has_kpp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Department::clear_kpp() {
  if (kpp_ != &::google::protobuf::internal::kEmptyString) {
    kpp_->clear();
  }
  clear_has_kpp();
}
inline const ::std::string& Department::kpp() const {
  return *kpp_;
}
inline void Department::set_kpp(const ::std::string& value) {
  set_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    kpp_ = new ::std::string;
  }
  kpp_->assign(value);
}
inline void Department::set_kpp(const char* value) {
  set_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    kpp_ = new ::std::string;
  }
  kpp_->assign(value);
}
inline void Department::set_kpp(const char* value, size_t size) {
  set_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    kpp_ = new ::std::string;
  }
  kpp_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Department::mutable_kpp() {
  set_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    kpp_ = new ::std::string;
  }
  return kpp_;
}
inline ::std::string* Department::release_kpp() {
  clear_has_kpp();
  if (kpp_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = kpp_;
    kpp_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Department::set_allocated_kpp(::std::string* kpp) {
  if (kpp_ != &::google::protobuf::internal::kEmptyString) {
    delete kpp_;
  }
  if (kpp) {
    set_has_kpp();
    kpp_ = kpp;
  } else {
    clear_has_kpp();
    kpp_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .Diadoc.Api.Proto.Address Address = 6;
inline bool Department::has_address() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Department::set_has_address() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Department::clear_has_address() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Department::clear_address() {
  if (address_ != NULL) address_->::Diadoc::Api::Proto::Address::Clear();
  clear_has_address();
}
inline const ::Diadoc::Api::Proto::Address& Department::address() const {
  return address_ != NULL ? *address_ : *default_instance_->address_;
}
inline ::Diadoc::Api::Proto::Address* Department::mutable_address() {
  set_has_address();
  if (address_ == NULL) address_ = new ::Diadoc::Api::Proto::Address;
  return address_;
}
inline ::Diadoc::Api::Proto::Address* Department::release_address() {
  clear_has_address();
  ::Diadoc::Api::Proto::Address* temp = address_;
  address_ = NULL;
  return temp;
}
inline void Department::set_allocated_address(::Diadoc::Api::Proto::Address* address) {
  delete address_;
  address_ = address;
  if (address) {
    set_has_address();
  } else {
    clear_has_address();
  }
}

// -------------------------------------------------------------------

// Box

// required string BoxId = 1;
inline bool Box::has_boxid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Box::set_has_boxid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Box::clear_has_boxid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Box::clear_boxid() {
  if (boxid_ != &::google::protobuf::internal::kEmptyString) {
    boxid_->clear();
  }
  clear_has_boxid();
}
inline const ::std::string& Box::boxid() const {
  return *boxid_;
}
inline void Box::set_boxid(const ::std::string& value) {
  set_has_boxid();
  if (boxid_ == &::google::protobuf::internal::kEmptyString) {
    boxid_ = new ::std::string;
  }
  boxid_->assign(value);
}
inline void Box::set_boxid(const char* value) {
  set_has_boxid();
  if (boxid_ == &::google::protobuf::internal::kEmptyString) {
    boxid_ = new ::std::string;
  }
  boxid_->assign(value);
}
inline void Box::set_boxid(const char* value, size_t size) {
  set_has_boxid();
  if (boxid_ == &::google::protobuf::internal::kEmptyString) {
    boxid_ = new ::std::string;
  }
  boxid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Box::mutable_boxid() {
  set_has_boxid();
  if (boxid_ == &::google::protobuf::internal::kEmptyString) {
    boxid_ = new ::std::string;
  }
  return boxid_;
}
inline ::std::string* Box::release_boxid() {
  clear_has_boxid();
  if (boxid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = boxid_;
    boxid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Box::set_allocated_boxid(::std::string* boxid) {
  if (boxid_ != &::google::protobuf::internal::kEmptyString) {
    delete boxid_;
  }
  if (boxid) {
    set_has_boxid();
    boxid_ = boxid;
  } else {
    clear_has_boxid();
    boxid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string Title = 2;
inline bool Box::has_title() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Box::set_has_title() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Box::clear_has_title() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Box::clear_title() {
  if (title_ != &::google::protobuf::internal::kEmptyString) {
    title_->clear();
  }
  clear_has_title();
}
inline const ::std::string& Box::title() const {
  return *title_;
}
inline void Box::set_title(const ::std::string& value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(value);
}
inline void Box::set_title(const char* value) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(value);
}
inline void Box::set_title(const char* value, size_t size) {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  title_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Box::mutable_title() {
  set_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    title_ = new ::std::string;
  }
  return title_;
}
inline ::std::string* Box::release_title() {
  clear_has_title();
  if (title_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = title_;
    title_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Box::set_allocated_title(::std::string* title) {
  if (title_ != &::google::protobuf::internal::kEmptyString) {
    delete title_;
  }
  if (title) {
    set_has_title();
    title_ = title;
  } else {
    clear_has_title();
    title_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .Diadoc.Api.Proto.Organization Organization = 3;
inline bool Box::has_organization() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Box::set_has_organization() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Box::clear_has_organization() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Box::clear_organization() {
  if (organization_ != NULL) organization_->::Diadoc::Api::Proto::Organization::Clear();
  clear_has_organization();
}
inline const ::Diadoc::Api::Proto::Organization& Box::organization() const {
  return organization_ != NULL ? *organization_ : *default_instance_->organization_;
}
inline ::Diadoc::Api::Proto::Organization* Box::mutable_organization() {
  set_has_organization();
  if (organization_ == NULL) organization_ = new ::Diadoc::Api::Proto::Organization;
  return organization_;
}
inline ::Diadoc::Api::Proto::Organization* Box::release_organization() {
  clear_has_organization();
  ::Diadoc::Api::Proto::Organization* temp = organization_;
  organization_ = NULL;
  return temp;
}
inline void Box::set_allocated_organization(::Diadoc::Api::Proto::Organization* organization) {
  delete organization_;
  organization_ = organization;
  if (organization) {
    set_has_organization();
  } else {
    clear_has_organization();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto
}  // namespace Api
}  // namespace Diadoc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Organization_2eproto__INCLUDED
